### PR TITLE
Added a view for devices on lan

### PR DESCRIPTION
**Pull request by kennethAltheaSystems**

### CODE REVIEW

**Comment by kennethAltheaSystems** [comment]
image

**Comment by kennethAltheaSystems** [comment]
image

**Comment by kennethAltheaSystems** [comment]
image

**Comment by kennethAltheaSystems** [comment]
image

**Comment by kennethAltheaSystems** [comment]
image

**Comment by kennethAltheaSystems** [comment]
image

**Review by jkilpatr — APPROVED** [review]

**Pull request merged**
